__author__ = 'yuyang'

# training_data_file_name = '../data/Baike/training/nlpcc-iccpol-2016.kbqa.training-data'
# testing_data_file_name = '../data/Baike/testing/nlpcc-iccpol-2016.kbqa.testing-data'
training_data_file_name = '../data/Baike/training/baike.sample.training-data'
testing_data_file_name = '../data/Baike/testing/baike.sample.testing-data'
# knowledge_base_file_name = '../data/NLPCC2016QA-Update/knowledge/nlpcc-iccpol-2016.kbqa.kb'
# knowledge_base_mention_file_name = '../data/NLPCC2016QA-Update/knowledge/nlpcc-iccpol-2016.kbqa.kb.mention2id'
knowledge_base_file_name = '../data/Baike/knowledge/baike.sample.kb'
knowledge_base_mention_file_name = '../data/Baike/knowledge/baike.sample.mention2id'
training_data_split_file_name = '../data/kbqa.process.data'
testing_data_split_file_name = '../data/kbqa.test.process.data'
# training_data_split_file_name = '../data/baike.process.data'
# testing_data_split_file_name = '../data/baike.test.process.data'
embedding_file_name = '../data/Baike/model/dbqa/dbqa.word2vec'  # .txt
training_data_result_file_name = '../data/res/kbqa/baike.training-data.res'
testing_data_result_file_name = '../data/res/kbqa/baike.testing-data.res'
testing_data_not_match_result_file_name = '../data/res/kbqa/baike.testing-data.not-match.res'

test_html = '../data/Baike/zhidao/s_0000.log'